### PR TITLE
scripts.logrotate: update logrotate script to avoid error.

### PR DESCRIPTION
**Pull request by mbugeia**
Avoid this error:
/etc/cron.daily/logrotate:
gzip: stdin: file size changed while zipping

### CODE REVIEW

**Comment by maranda** [comment]
Could you please update/reopen the pull request changing the commit title to:
scripts.logrotate: update logrotate script to avoid error.

All commit titles *must* have the affected filenames prepended to.

**Comment by mbugeia** [comment]
It's done.

**Comment by maranda** [comment]
No the actual commit, not the issue title.

**Comment by mbugeia** [comment]
Sorry I'm going on vacation now and do not have access to git. Please do the proper commit and close this PR thanks ;)

**Pull request closed without merging**
